version: '3.8'

services:
  # 多语言服务
  language-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: language-service
    restart: unless-stopped
    ports:
      - "3100:3100"
    environment:
      LANGUAGES_NODE_ENV: "production"
      LANGUAGES_PORT: "3100"
      LANGUAGES_HOST: "0.0.0.0"
      LANGUAGE_DATABASE_URL: "postgresql://postgres:123456789@postgres:5432/languages?schema=public"
      LANGUAGE_REDIS_URL: "redis://redis:6379"
      LANGUAGE_REDIS_PASSWORD: ""
      LANGUAGE_REDIS_PREFIX: "lang:"
      LANGUAGE_API_RATE_LIMIT: "100"
      LANGUAGE_API_RATE_LIMIT_TIMEWINDOW: "60000"
      LANGUAGE_CORS_ORIGIN: "*"
      LANGUAGE_LOG_LEVEL: "info"
      DOCKER_CONTAINER: "true"
    depends_on:
      - postgres
      - redis
    networks:
      - language-network

  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: language-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "languages"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - language-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: language-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - language-network

networks:
  language-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
